name: DisableChatForMe
main: DisableChatForMe\DisableChatForMe
version: 1.0.3
author: xpyctum
api: [1.9.0]
load: POSTWORLD
commands:
 chaton:
  description: "Player can see chat"
  permission: dcfm.chaton
 chatoff:
  description: "Player can't see chat"
  permission: dcfm.chatoff